### ISSUE TITLE
Data structure for cluster_to_point_map

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-gamma#19]
I took a *very brief* look at your `code/exploratory_analysis/kmeans.py` and noticed your cluster_to_point_map structure. It looks like a lot of the code is dedicated to mapping/unmapping from this structure.

When you have a data structure where you'd like to map one thing to another, a dictionary is really nice as you don't have to traverse the whole structure to find the value you want.

This is just a comment - it's not necessary that you change your structure. I just wanted to point it out so you could think about it for a couple seconds and see if you could formulate your structure as a dictionary instead of an ordered list.

**Comment by rossbar** [comment]
Nice work on your code by the way! Keep it up! :+1:

**Comment by LiamFengLin** [comment]
Hi!

That cluster_to_point_map is already a dictionary. It maps from a cluster to all the points in that cluster. The problem is that the merging strategy described in the paper often requires a reverse mapping from points to clusters. I could have built another map from point to its assigned cluster at that stage. I didn't build it because the data structure is only an intermediate step.

I'll see what I can do to optimize this method.

Thanks!

**Comment by rossbar** [comment]
Like I said, it was based on a *very* cursory glance at your code... don't spend undue time worrying about it, you have more important things to worry about!
