### ISSUE TITLE
meeting

### ISSUE THREAD

**Issue by jarrodmillman** [berkeley-stat159/project-gamma#35]
Did we schedule a meeting for this week to discuss your project as a group?

**Comment by LiamFengLin** [comment]
Hi Jarrod! I'm so sorry. I forgot to create the issue here GitHub to track the meeting. 

The meeting is 9:00 to 10:00 am this coming Monday.

**Comment by LiamFengLin** [comment]
Hi @jarrodmillman, 

Thank you for your time!

I didn't add you in my reply above so I added you here to make sure you can receive my reply. 

You mentioned that you want to me to set a meeting time on GitHub. Is opening this issue sufficient (I can't find a specific calendar feature on GitHub)? 

About the meeting, we plan to present to you the very clear flow of our entire project (on whiteboard or otherwise). Then we will show you some results and considerations for each component along our analysis. We don't plan to get down to the specifics of code implementation in the meeting but will try to push out as much as work onto GitHub before tonight. 

Enjoy your weekend!
Team Gamma
